model_initializer:
  summarization:
    model_id: "facebook/bart-large-cnn"
  conversation:
    model_id: "NousResearch/Llama-2-7b-chat-hf"
    max_new_tokens: 80
    temperature: 0.7
    top_k: 50
    quantization_bits: 8
